version: "3"

services:
  webapp:
    build: ./
    ports:
      - "3000:3000"
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx/:/etc/nginx/condf.d/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"