apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        service: webapp
    spec:
      imagePullSecrets:
        - name: secret-registry
      containers:
        - image: 501853673872.dkr.ecr.us-east-1.amazonaws.com/prueba
          name: webapp
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always