apiVersion: v1
kind: Service
metadata:
  labels:
    service: webapp
  name: webapp
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: webapp
status:
  loadBalancer: {}
